### ISSUE TITLE
Usage with hiera and 'include'

### ISSUE THREAD

**Issue by erikanderson** [thias/puppet-sysctl#39]
I am used to including classes within roles. I tried to do this within our `puppetmaster` role: 
```
class role::puppetmaster {
...
include ::sysctl
...
```
and set up values in hiera: 
```
sysctl::base::values:
  net.core.netdev_max_backlog:
    value: '2500'
  net.core.rmem_max:
    value: '16777216'
  net.core.wmem_max:
    value: '16777216'
```

When I run this I get: `Error while evaluating a Function Call, Could not find class ::sysctl`

Looking through the code I see that `sysctl` is set up as a define, and not a class. 

My question is: how can I include sysctl in a way that it will pick up the hiera values? I tried including `::sysctl::base` but that did not seem to change anything
